include:
  - project: creators/ci-templates
    ref: main
    file: /mlc-sync.gitlab-ci.yml

variables:
  #
  # **ここから：案件ごとに必ず設定してください**
  #
  # デモサイトの種類
  # hoge.comの場合はmerlot
  # huga.comの場合はaligote
  MLC_SYNC_HOST: merlot
  #
  # **↓↓↓↓↓重要：必ず確認↓↓↓↓↓**
  # デモサイトの名前（xxx.hoge.comやxxx.huga.comのxxx）
  MLC_SYNC_DOMAIN: ___dummy___
  # **↑↑↑↑↑重要：必ず確認↑↑↑↑↑**
  #
  # デモのルートディレクトリに対応するディレクトリ名
  MLC_SYNC_ROOT: public
  #
  # サブディレクトリのみ同期したい場合は次の行のコメントを外して（#とその次の空白を削除して）サブディレクトリ名を記載
  # MLC_SYNC_SUB_DIRECTORY:
  #
  # 同期するブランチ名
  MLC_SYNC_BRANCH: demo
  # **ここまで：案件ごとに必ず設定してください**
  #
  # 同期ユーザー名
  MLC_SYNC_USER: $MLC_SYNC_DOMAIN
  #
  # 詳細なログを表示したい場合は次の行のコメントを外す（#とその次の空白を削除）
  # MLC_SYNC_VERBOSE: 1

mlc-sync:
  script:
    #
    # **ここから：案件ごとに設定してください**
    #
    # コンテンツ生成前にリントやテストを行うコマンドを記述
    # なければ何も書かない
    - npm ci
    # - npm i
    #
    # コンテンツを生成するコマンドを記述
    # なければ何も書かない
    - npm run build
    #
    # コンテンツ生成後にリントやテストを行うコマンドを記述
    # なければ何も書かない
    - npm run lint:ejs
    - npm run lint:scss
    - NODE_TLS_REJECT_UNAUTHORIZED=0 npm run lint:vlint
    #
    # **ここまで：案件ごとに設定してください**
    #
    - echo "mlc-sync"
